### ISSUE TITLE
forge port

### ISSUE THREAD

**Issue by shellduck8** [DeltaTimo/elytra-flight-hud#4]
Hello, how do I port it to forge 1.18.2? I need this for my millitairy modpack to play with my friends.

**Comment by franzitrone** [comment]
Greetings,

I'm out of the loop with how Forge works. First off, you'll probably have to find out what the Forge equivalent of `HudRenderCallback.EVENT.register` is in Forge and then perhaps porting could be "easy".

Good luck and best regards!
